version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: ${MONGO_CONTAINER_NAME}
    command: mongod --port ${MONGO_PORT}
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js  # Mount initialization script
    env_file:
      - .env

  task-server:
    image: toficzak/task_server:0.0.3
    container_name: task-server
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - mongodb
    env_file:
      - .env

  task-client-cli:
    image: task-client-cli:0.0.1
    container_name: task-client-cli
    environment:
      - tcc_base_url=http://task-server:8080
    depends_on:
      - task-server

volumes:
  mongodb_data:
    driver: local
